version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tempo
    main: ./cmd/tempo
    binary: tempo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: indaco
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/indaco/tempo
    description: A CLI tool for managing assets and scaffolding components in [templ](https://templ.guide)-based projects
    license: MIT
    install: |
      bin.install "tempo"
    test: |
      system "#{bin}/tempo", "--version"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
