version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tempo
    main: ./cmd/tempo
    binary: tempo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']

homebrew_casks:
  - name: tempo
    repository:
      owner: indaco
      name: homebrew-tap
    directory: Casks
    homepage: https://github.com/indaco/tempo
    description: A CLI tool for managing assets and scaffolding components in templ-based projects.
    binaries:
      - tempo
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tempo"]
          end

changelog:
  disable: true
