name: Create GitHub Release from Commit Message

on:
  push:
    branches:
      - main

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract_version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ chore:\ release\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="v${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            exit 1
          fi

      - name: Read release notes
        id: read_notes
        run: |
          NOTES_FILE=".changes/${{ steps.extract_version.outputs.version }}.md"
          if [[ -f "$NOTES_FILE" ]]; then
            RELEASE_NOTES=$(cat "$NOTES_FILE")
            echo "release_notes<<EOF" >> $GITHUB_OUTPUT
            echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
          make_latest: 'true'
          token: ${{ secrets.TEMPO_TOKEN }}
          body: ${{ steps.read_notes.outputs.release_notes }}
          generate_release_notes: true
